### ISSUE TITLE
Remove unused columns from projects

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon-legacy#1452]
Suggest we remove these columns and any related code from `projects` table:
- [x] description
- [x] project_type_id
- [ ] is_private (only after we've updated the public_templates_enabled column)
- [x] is_enabled
- [x] current_plan
- [x] storage_usage
- [x] processing_usage
- [x] pattern_matching_enabled
- [x] cnn_enabled
- [x] aed_enabled
- [x] clustering_enabled
- [x] featured
- [x] image
- [x] reports_enabled

**Comment by rassokhina-e** [comment]
@koonchaya can you please check these test cases on the staging side:
* create a new project
* update the project
* go to any analysis pages and can see these pages (PM, AED, Clustering)
* Redirect from the legacy arbimon to new Arbimon pages from the sidebar
* create a new site
* edit the site

**Comment by koonchaya** [comment]
Test results
- create a new project ✅ 
- update the project 
  - update on project settings ✅
  - upload recordings ✅
  - create PM job ✅
- go to any analysis pages and can see these pages (PM, AED, Clustering) ✅
- Redirect from the legacy arbimon to new Arbimon pages from the sidebar ✅
- create a new site ✅
- edit the site ✅

**Comment by rassokhina-e** [comment]
[all_projects_export.csv](https://github.com/user-attachments/files/15913847/all_projects_export.csv)
