### ISSUE TITLE
User doesn't get all PM export from  biosoundscape project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1561]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1717598848034249

Our favorite PM-bulk-export project is at it again (lol). This project ran another PM bulk export 3 days ago and haven't gotten anything.
I know we had errors with this project before but had fixed them - Can you confirm that this export is indeed running?https://arbimon.org/p/biosoundscape

**Comment by rassokhina-e** [comment]
I tested the huge PM export for the biosoundscape project and checked the memory leak (attached image). The memory usage was reduced by refactored code, so we just need to retest it on the real project after the production release

![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/a147fff5-7d4d-424b-95da-11fbcda6cecf)

**Comment by rassokhina-e** [comment]
@koonchaya please check the PM export on the staging side

**Comment by koonchaya** [comment]
@rassokhina-e I haven't got the PM export that I requested from staging.

**Comment by rassokhina-e** [comment]
@koonchaya Fixed

**Comment by rassokhina-e** [comment]
Hi @carlybatist ! Can you please run export al PM jobs on the biosoundscape project?

**Comment by koonchaya** [comment]
@carlybatist @rassokhina-e I will do it.

**Comment by koonchaya** [comment]
Exported files match with jobs



![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/f9b29fd2-00ff-4f9a-9d9e-92caab738855)
