### ISSUE TITLE
Legacy - update permissions for user and data entry role

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1566]
Change the permissions for user and data entry role following these
- [x] User and data entry can upload and export recordings, but CANNOT delete recordings 
- [x] User can create and edit jobs but CANNOT delete them
- [x] User and data entry CANNOT delete species

**Comment by rassokhina-e** [comment]
@koonchaya can the expert role:
`User can create and edit jobs but CANNOT delete them`

**Comment by koonchaya** [comment]
>User can create and edit jobs but CANNOT delete them
This is for the User role

**Comment by rassokhina-e** [comment]
I see from the permissions the expert can delete jobs, is it correct @koonchaya ?

**Comment by rassokhina-e** [comment]
can the expert and the user export PM and soundscapes jobs? @koonchaya

**Comment by koonchaya** [comment]
Expert can export jobs but User cannot export jobs

**Comment by koonchaya** [comment]
- [ ] User should be able to edit job

![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/6388f7d5-2ad9-445e-a6df-e3ec3fb2195d)

- [ ] User should be able to export sites 

![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/735bacd8-88cf-4c58-ac76-1bd3aa37e422)


- [ ] User and data entry should be able to export recordings

- [ ] Data entry should not be able to delete recordings 




- [ ] Data entry should not be able to deleted species in the project

- [ ] Data entry clicks export sites and redirected to a new page with data and an error page. Data entry should be able to export sites.



![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/fd72a0f3-e5ad-477e-aa6e-637e8431a8b9)



![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/1d59fe8d-8249-4ccc-a817-1f2be9c4d323)

**Comment by rassokhina-e** [comment]
can you please check this case @koonchaya on the staging side

**Comment by koonchaya** [comment]
- [ ] User should not be able to export job
- [ ] User should be able to export sites. See what I can see after export from screenshot 

![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/57ecceba-fd33-4a83-a1a6-6c197aeba3bd)


- [ ] Data entry clicks export sites and redirected to a new page with data and an error page. Data entry should be able to export sites.



![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/1e2d1b69-4cf9-47c4-b49f-70b2f7bf8780)

**Comment by rassokhina-e** [comment]
> User should not be able to export job


![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/fe0c6912-ff9e-4e1e-bc84-eafb02acdb0e)



![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/eb0646cb-e548-4f93-a23e-c15b320962df)
![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/e27f8ff6-09b4-49a5-aedf-6ba89a693d81)
![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/bbbac2e4-7e36-4346-a875-3149408d3a7c)

**Comment by rassokhina-e** [comment]
>User should be able to export sites. See what I can see after export from screenshot

this is my file for the BCI project on staging for the User role



[sites-export.csv](https://github.com/user-attachments/files/15905839/sites-export.csv)

**Comment by rassokhina-e** [comment]
>Data entry clicks export sites and redirected to a new page with data and an error page. Data entry should be able to export sites.




![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/1dc43b3c-d461-44b0-bd3e-ee4ff6d19e14)



[sites-export (1).csv](https://github.com/user-attachments/files/15905855/sites-export.1.csv)



![Image](https://github.com/rfcx/arbimon-legacy/assets/31901584/1c484e6d-b398-4433-8ac2-bf67fdf7a2f6)

**Comment by koonchaya** [comment]
@rassokhina-e I used safari when I exported sites that's why I didn't get the files but got the data from a new page instead.

**Comment by rassokhina-e** [comment]
@koonchaya okay, can we create a small ticket for the safari export, I mean do not fix it with this task related to the roles update
