### ISSUE TITLE
User cannot import sites with csv

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1572]
Original post https://rfcx.slack.com/archives/C03FD1WD02J/p1719949292237179

A user has reported getting a server error when trying to bulk-import a CSV file of sites in this project

Project: https://arbimon.org/p/espacypa/overview

csv files 👉  https://rfcx.slack.com/files/U04HL3HL6JX/F07APAJ2929/espacypag_gps.csv

@carlybatist tried to import but there was server error.

![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/983d6165-8a76-40fd-892d-c0bbdae18e67)

**Comment by koonchaya** [comment]
I tried to import sites with csv to my project but I fixed the data inside the file. There are the numbers that saved as text I think it cause the error, so I changed them to numbers format. I can import sites but there are 200 sites in file. I only see 22 sites in the project after I imported the csv. My test project https://arbimon.org/project/test-import-sites-with-csv-1/audiodata/sites

**Comment by rassokhina-e** [comment]
we found a problem with using a long latitude value after the dot. The maximum size should be not more than 13 numbers after the dot. Tree will attest it and update the logic on the arbimon side. So we should not send any messages to the user about this, because we have to handle this case ourselves

@koonchaya

**Comment by carlybatist** [comment]
fyi @koonchaya @rassokhina-e the user figured this out too and was able to upload the CSV with shorter decimal places

<img width="993" alt="Screenshot 2024-07-04 at 9 47 16 AM" src="https://github.com/rfcx/arbimon-legacy/assets/46716228/b62f77b4-e752-4c1d-8e36-2a325247044a">

**Comment by RatreeOchn** [comment]
![Image](https://github.com/rfcx/arbimon-legacy/assets/51106210/7d7bf0db-a6db-4d0f-a641-ccad9eda4d6b)



![Image](https://github.com/rfcx/arbimon-legacy/assets/51106210/bd20f4a3-e67c-4402-9ada-05cf13ae5905)
