### ISSUE TITLE
Add ability to export multiple PM jobs

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1578]
User should be able to select multiple jobs to export instead of all jobs.

- [ ] UI design
- [ ] Should we have limitation selecting jobs at a time?

**Comment by RatreeOchn** [comment]
<img width="1107" alt="Screenshot 2567-09-25 at 09 41 39" src="https://github.com/user-attachments/assets/2a0894a9-e67f-40fc-9a76-3aac4ba075ba">

<img width="1256" alt="Screenshot 2567-09-25 at 09 35 00" src="https://github.com/user-attachments/assets/d73b3987-9ecd-48ab-a38a-95e066d410b7">

<img width="1257" alt="Screenshot 2567-09-25 at 09 35 28" src="https://github.com/user-attachments/assets/6092985e-178f-4a53-9de3-2eb1f2f5e076">

<img width="1251" alt="Screenshot 2567-09-25 at 09 36 02" src="https://github.com/user-attachments/assets/2345dbd2-c83a-49bb-b60a-5b7d9a666083">

**Comment by RatreeOchn** [comment]
Update follow feedback 
https://www.figma.com/board/EL47z8RYxZjHd1VVKBdZCD/Untitled?node-id=0-1&t=iSLGq4zGWsFDpYux-1

<img width="1335" alt="Screenshot 2567-09-25 at 11 15 16" src="https://github.com/user-attachments/assets/d159dcf6-f6ff-415f-8dd2-3114d21be25f">

**Comment by rassokhina-e** [comment]
The PR project has a lot of jobs, the user might not be comfortable to select 200 jobs in this way, my suggestion is to make a dropdown with all jobs and search input to search by name/template and species name

**Comment by rassokhina-e** [comment]
@koonchaya what do you think?

**Comment by RatreeOchn** [comment]
Users can search from this input box. @rassokhina-e 

<img width="1251" alt="Screenshot 2567-09-25 at 10 57 35 copy" src="https://github.com/user-attachments/assets/9016ca9f-cd1d-4105-9fea-f209e521b791">

**Comment by rassokhina-e** [comment]
looks good!

**Comment by RatreeOchn** [comment]
Update!

- When nothing has been selected.
<img width="1254" alt="Screenshot 2567-09-27 at 12 41 22" src="https://github.com/user-attachments/assets/8133ce66-06ea-4b8d-8b6b-3fd342610c05">

- Once selected, the selected count, the Clear button, and the Export button will be displayed.
<img width="1259" alt="Screenshot 2567-09-27 at 12 38 42" src="https://github.com/user-attachments/assets/05901f2c-11ca-4897-be40-5182a2443d0c">

**Comment by RatreeOchn** [comment]
Update design (Option 2)

<img width="1254" alt="Screenshot 2567-09-30 at 11 16 26" src="https://github.com/user-attachments/assets/dc8fb4ca-c037-4b8b-8f6b-3d015980fcb7">

**Comment by koonchaya** [comment]
![Image](https://github.com/user-attachments/assets/6bb977ac-e242-46c6-9322-452ac5e50dc5)
![Image](https://github.com/user-attachments/assets/8af233c3-8925-4800-95a5-8fd90c3211dd)
![Image](https://github.com/user-attachments/assets/bd9c36e5-f25a-4010-8c66-7c31237e8f19)
