### ISSUE TITLE
Add color themes to spectrograms

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1579]
User can change the spectrograms color themes. We will need to research on which color would work or how it is important.

- [ ] UI design
- [x] Greyscale is default
- [x] Update media api

**Comment by rassokhina-e** [comment]
![IMG_2680](https://github.com/user-attachments/assets/037c3e6e-8008-405e-b03e-c45ea84520d3)


I have to improve images

**Comment by koonchaya** [comment]
Name of the colors 
- Greyscale
- Purple-Blue
- Red-Blue
- Brown-Green
- Orange-Yellow
![Image](https://github.com/user-attachments/assets/a1fcbe87-3134-4cf5-98ca-0119172e55cb)
