### ISSUE TITLE
Soundscape job in waiting status

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1580]
From [zcolonp@gmail.com](mailto:zcolonp@gmail.com)

Project https://arbimon.org/project/elevationgradient-elyunque

> I was able to run the soundscapes of my sites, but I tried to do the same playlists, subsetting my recordings by sampled seasons, but the jobs have been waiting since yesterday at 1 p.m. Is that normal, or is there any bug in the soundscape analyzer? We got an error 403 in one of the attempts. I tried using a different computer and user today, but they are still waiting.

**Comment by RatreeOchn** [comment]
Jobs is processing.
<img width="502" alt="Screenshot 2567-09-24 at 11 54 39" src="https://github.com/user-attachments/assets/d74b2239-698c-44b7-89ec-bdd6d5cb4da3">

<img width="925" alt="Screenshot 2567-09-24 at 11 54 54" src="https://github.com/user-attachments/assets/afa26c19-96d7-4998-b265-463812536fec">
