### ISSUE TITLE
User cannot export PM

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1581]
From lironisraely@mail.tau.ac.il

User cannot export PM result from their project. I checked in other projects the export worked.

> I have run several pattern-matching analyses on all the data sets, but I cannot download or export the data from these analyses.
> Whenever I click the download bottom the computer is thinking for long and then the following message appears:
> "This page is not working
> 

Project https://arbimon.org/project/riparian-biodiversity/analysis/patternmatching

![Image](https://github.com/user-attachments/assets/5e072abf-9d32-472d-96d1-ee509d6d25bd)

**Comment by rassokhina-e** [comment]
I sent all pm jobs to @koonchaya by exporting all pm jobs logic

**Comment by koonchaya** [comment]
This is where user got the error from 

![Image](https://github.com/user-attachments/assets/1363c6dc-df56-4049-9a0d-036ad54e865b)


This is the example job result (>100k results)

![Image](https://github.com/user-attachments/assets/bddbe7aa-c76b-414c-8c09-6e3f23535e46)

**Comment by koonchaya** [comment]
I share all PM export with the user for the workaround.

**Comment by rassokhina-e** [comment]
The idea is to move export particular jobs logic to the export job we use for the PM. So once Tree implement it on the PM jobs list page we can hide this logic inside the details page. This internal export on the details page doesn't work with huge jobs, so we have to process this requests by export job on the kubernetes side
