### ISSUE TITLE
[Arbimon Legacy] combine uri to get models data

### ISSUE THREAD

**Issue by rassokhina-e** [rfcx/arbimon-legacy#1597]
ref: https://github.com/rfcx/arbimon-db/issues/20

old uri `project_3/models/job_151_7_1.mod`

replace old uri with new columns, combine them
* uri_param1 (tinyint) - 151
* uri_param2 (tinyint) - 7
* uri_param3 (tinyint) - 1

**Comment by Tooseriuz** [comment]
the size of the table is 0.64 MB. it is not worth cleansing at the moment.
