### ISSUE TITLE
Change tag color on visualizer when change spectrogram color

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1608]
Improve tag color to be visible easily on each spectrogram theme.

![Image](https://github.com/user-attachments/assets/0c935be7-fd8a-4ae6-ab08-43be298fa94e)
![Image](https://github.com/user-attachments/assets/ca1695d2-032b-4357-b437-ff939b6f87c2)
![Image](https://github.com/user-attachments/assets/085b09e0-09af-4466-a1bf-02e46381a4a0)
![Image](https://github.com/user-attachments/assets/6a79af4b-a31b-4be5-afea-8e2e69e25a5b)

**Comment by RatreeOchn** [comment]
```
color:  #2D4BA5;
opacity: 0.6;
```

<img width="868" alt="Screenshot 2567-10-09 at 15 02 50" src="https://github.com/user-attachments/assets/27155e2e-9b85-48f8-b426-563121679f05">

<img width="886" alt="Screenshot 2567-10-09 at 15 03 11" src="https://github.com/user-attachments/assets/e50fb532-66aa-4058-82e4-d83ebb8d9059">

<img width="877" alt="Screenshot 2567-10-09 at 15 03 30" src="https://github.com/user-attachments/assets/c960c61a-cb88-488a-b742-f13a984522b6">

<img width="885" alt="Screenshot 2567-10-09 at 15 03 59" src="https://github.com/user-attachments/assets/09598bcb-845f-4b9f-b6fd-27eccce2470d">

<img width="888" alt="Screenshot 2567-10-09 at 15 04 27" src="https://github.com/user-attachments/assets/1208d966-949c-4f2e-b955-c1aaea0d0bf1">

**Comment by RatreeOchn** [comment]
```
background: rgba(255, 255, 255, .5)
color: #1E1C13;
```
<img width="890" alt="Screenshot 2567-10-10 at 11 38 39" src="https://github.com/user-attachments/assets/284dbce5-0822-402e-b04d-e994cf3851d1">

<img width="893" alt="Screenshot 2567-10-10 at 11 39 51" src="https://github.com/user-attachments/assets/b972ac18-8215-4391-83d5-77de577624c6">

<img width="890" alt="Screenshot 2567-10-10 at 11 40 13" src="https://github.com/user-attachments/assets/475130d9-d12c-44dd-a9c3-6e005a092c17">

<img width="867" alt="Screenshot 2567-10-10 at 11 42 21" src="https://github.com/user-attachments/assets/1cfa4062-939e-4763-aa49-bf803d323c62">

<img width="882" alt="Screenshot 2567-10-10 at 11 43 40" src="https://github.com/user-attachments/assets/35673b16-da21-4d29-b8d4-fec61a4a3d8d">
