### ISSUE TITLE
Classification export column name meaning

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1635]
From: carine.cola@posgrad.inpa.gov.br

- [ ] what is the meaning of the column named "Vector max value" in the classification export?

![Image](https://github.com/user-attachments/assets/ba991996-4554-4d3b-b967-71045bf7e80a)

- [x] why did I export from . There are 3 columns missing from the export.

[the-green-place-phitsanulok](https://arbimon.org/project/the-green-place-phitsanulok/analysis/random-forest-models/models) 
![Image](https://github.com/user-attachments/assets/4b84bb8a-b7d5-4de7-ac33-f8bc64733966)

[bci-panama-2018](https://arbimon.org/project/bci-panama-2018/analysis/random-forest-models/models)
 ![Image](https://github.com/user-attachments/assets/d8c47efd-92cf-4a0a-af6d-c163c704dd22)

**Comment by rassokhina-e** [comment]
Hi @koonchaya ! The reason of 3 missed columns in the report related to `threshold` value, if the csv file which we get from s3 skipped this value, then 3 column also do not include to the export file.

the current csv file shows null value for the threshold, we need to find a reason!

```
year: 2022,
    month: 3,
    day: 1,
    hour: 3,
    min: 39,
    threshold: null,
    uri: 'project_1902/models/job_110749_1464_1.mod',
    ruri: '2022/02/28/w4tcg5n72ylb/bb84be4f-a8e2-4f1a-9589-b65726908f52.opus',
    meta: {
      filename: 'k9s1g9glfkjw_2022-03-01T03-39-06.035+0530_24kHz_91.264secs.opus'
    },
    mvv: 0.0959658,
    rec: 'k9s1g9glfkjw_2022-03-01T03-39-06.035+0530_24kHz_91.264secs.opus',
    present: 1,
    name: 'test upload',
    scientific_name: 'Amaurornis phoenicurus',
    songtype: 'Common Song'
    ```

**Comment by rassokhina-e** [comment]
the threshold we put in the model before creation the classification job, here
<img width="549" alt="Screenshot 2024-11-15 at 19 58 09" src="https://github.com/user-attachments/assets/3cc565ba-312c-4f7f-bab3-b28373ae2b7e">

**Comment by rassokhina-e** [comment]
the report includes 3 missed columns now
[test_threshold.csv](https://github.com/user-attachments/files/17778686/test_threshold.csv)

**Comment by rassokhina-e** [comment]
`Vector max value` is a maximum vector from array of the point related to sample rate of the particular recording.

@koonchaya can you please make sure with this description above with Ant before texting to the user

**Comment by koonchaya** [comment]
The Vector max value is the score. We are using scikit-learn, and the RandomForestClassifier. See more information https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html.
